import type { Metadata } from "next";
import "./globals.css";
import { aeonik } from "./fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${aeonik.variable} antialiased`} suppressHydrationWarning>
        {children}
      </body>
    </html>
  );
}
